server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springJpa?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka, http://localhost:9999/eureka